name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: git fetch --prune --unshallow

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: vet
        run: go vet ./...

      - name: test
        run: go test --race ./...
