on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: git fetch --prune --unshallow

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: vet
        run: go vet ./...

      - name: test
        run: go test --race ./...

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
